#ifndef LICOM3_KOKKOS_SRC_HEAD_FORTRAN_MSG_MOD_H_
#define LICOM3_KOKKOS_SRC_HEAD_FORTRAN_MSG_MOD_H_

#include "def-undef.h"

#ifdef LICOM_ENABLE_FORTRAN_COMPILER_INTEL
extern int msg_mod_mp_nproc_;
#endif // LICOM_ENABLE_FORTRAN_COMPILER_INTEL

#ifdef LICOM_ENABLE_FORTRAN_COMPILER_GNU
extern int __msg_mod_MOD_nproc;
#endif // LICOM_ENABLE_FORTRAN_COMPILER_GNU

#endif // LICOM3_KOKKOS_SRC_HEAD_FORTRAN_MSG_MOD_H_
