#ifndef LICOM3_KOKKOS_SRC_HEAD_CPP_POP_DISTRIBUTION_MOD_H_
#define LICOM3_KOKKOS_SRC_HEAD_CPP_POP_DISTRIBUTION_MOD_H_
#include "def-undef.h"
#ifndef LICOM_ENABLE_FORTRAN

// #ifdef LICOM_ENABLE_FORTRAN_COMPILER_INTEL
// extern "C" void pop_distributionmod_mp_pop_distributiongetall()
// #endif // LICOM_ENABLE_FORTRAN_COMPILER_INTEL

// #ifdef LICOM_ENABLE_FORTRAN_COMPILER_GNU
// #endif // LICOM_ENABLE_FORTRAN_COMPILER_GNU

#endif // LICOM_ENABLE_FORTRAN
#endif // LICOM3_KOKKOS_SRC_HEAD_CPP_POP_DISTRIBUTION_MOD_H_