#!/usr/bin/bash
#DATAPATH=/work1/esm7/licom/data/10km
# sw
DATAPATH=/home/export/online1/mdt00/shisuan/swiap/licom/huangjian/data/10km

ln -sf ${DATAPATH}/mecator-salt-20160501-3600X2302X55_n2s.nc salt_initial
ln -sf ${DATAPATH}/mecator-temp-20160501-3600X2302X55_n2s.nc temp_initial
ln -sf ${DATAPATH}/chl_clim_monthly_tripole_3600X2302X55_omip_db_20170529.nc MODEL_CHLFRC

ln -sf ${DATAPATH}/ice.2016_daily.nc ice.2016_daily.nc
ln -sf ${DATAPATH}/q_10.2016_daily.nc q_10.2016_daily.nc
ln -sf ${DATAPATH}/rain.2016_daily.nc rain.2016_daily.nc
ln -sf ${DATAPATH}/rlds.2016_daily.nc rlds.2016_daily.nc
ln -sf ${DATAPATH}/rsds.2016_daily.nc rsds.2016_daily.nc
ln -sf ${DATAPATH}/runoff_all.2016_daily.nc runoff_all.2016_daily.nc
ln -sf ${DATAPATH}/slp.2016_daily.nc slp.2016_daily.nc
ln -sf ${DATAPATH}/snow.2016_daily.nc snow.2016_daily.nc
ln -sf ${DATAPATH}/sss_month_phc3_tripole_3600X2302X55_omip_db_20170529.nc sss_phc3_monthly.nc
ln -sf ${DATAPATH}/t_10.2016_daily.nc t_10.2016_daily.nc
ln -sf ${DATAPATH}/tidal_energy_licom_tripole_3600X2302X55_omip_db_20170529.nc tidal_energy.nc
ln -sf ${DATAPATH}/u_10.2016_daily.nc u_10.2016_daily.nc
ln -sf ${DATAPATH}/v_10.2016_daily.nc v_10.2016_daily.nc

ln -sf ${DATAPATH}/depth.da depth.da
ln -sf ${DATAPATH}/grid.da grid.da
ln -sf ${DATAPATH}/kmt.da kmt.da
ln -sf ${DATAPATH}/dncoef.h1 dncoef.h1
ln -sf ${DATAPATH}/fort.22.0002-01-05 fort.22.0002-01-05
cp ${DATAPATH}/rpointer.ocn rpointer.ocn
cp ${DATAPATH}/ocn.parm ocn.parm


#Tsinitial LOWRES
#latlon-area.nc
